### ISSUE TITLE
Variables Cache

### ISSUE THREAD

**Issue by ghost** [Sentilix/sota#1]
Hey, I can't find where the variables are saved, for example, auction time, Boss DKP etc.

Auction Time i don't get at all, in the `sota-core.lue` is says:

``` SOTA_CONFIG_AuctionTime			= 20 ```

but in game it always gives 25s?

Cheers

**Comment by ghost** [comment]
nvm, found it in SavedVariables/SotA.lua

**Comment by Sentilix** [comment]
Good you found the value - I was about to dig up the code :-)
