### ISSUE TITLE
SotA causing dc/crash?

### ISSUE THREAD

**Issue by Lotis45** [Sentilix/sota#2]
Hello, 

My guild has been using SotA now for a few months and it's a great system for tracking dkp. We have found however that since intalling the addon our officers experience far more crashes/disconnections than they did in the past (mostly DC's, full crashes may be coincidence). 

I am not 100% sure it is related to SotA except that only those who have the addon installed and use commands during raids seem to get bombarded with constant DC's (sometimes 10+ a raid). The issue seems to get worse as the raid progresses as well and by the time we reach Rag in MC for example, its difficult for the master-looter to stay online long enough to distribute loot.

I have disabled any addon I have seen/read is incompatible with SotA and tried adjusting settings in WoW but so far have no found a solution. Do you have any idea what cause behavior like this if in fact it could be related to SotA? Thanks!

**Comment by Sentilix** [comment]
I might have one idea. If you raid alot, the history information keeps increasing, and if it consume all memory a client crash *might* happen.

Try this and let me know if it helps: `/script SOTA_HISTORY_DKP = {};`

This will reset the History but not change any DKP. If this is indeed the cause, I'll have to implement some handling of this; e.g. max 1000 lines or last 7 days or whatever. And a manual reset button :-)

Thanks for the report btw.

**Comment by Sentilix** [comment]
I am closing this since I haven't heard further information.

However; in release 1.2.0 I've added a "Purge DKP History" button which does the same as the above command. Hopefully that fix the crashes.
