### ISSUE TITLE
Silent Bidding Support

### ISSUE THREAD

**Issue by vschumaker** [Sentilix/sota#3]
I would like to use the bidding feature, but my guild uses a silent bidding system.

**Comment by Sentilix** [comment]
There is not directly support for it, but in the current 1.2 version in the works you can do a workaround.

All messages in the auction interface can be reconfigured, meaning you can leave out bids or names.
The bidding itself can be done using whispers, so in this way you *could* do it silently and/or anonymously.

Note that the 1.2 version is not yet stable. It seems to work OK but there are probably bugs here'n'there.

**Comment by Sentilix** [comment]
SotA 1.2 is now released. In the MESSAGE configuration you can now change or disable the messages printed during an auction. Bidding can be taken by whispers (as always).
