### ISSUE TITLE
DKP for offliners

### ISSUE THREAD

**Issue by Driftyz** [Sentilix/sota#4]
Greetings from CE on VG. :)

We would like to add dkp to the offliners aswell when awarding boss kill dkp. The reason is that most of the time our queue logs off to save buffs. From what I can see in the addon code it requests that the person is online to award dkp, so we can probably rewrite it without much problems, but I'd rather ask for this as a built in feature instead.

Also, when testing the newest version, I'm getting SOTA_CONFIG_MESSAGES[OnDKPAddedRaid] was not found (and similar for every event add/subtract dkp).

edit: just noticed that it does add to queue offliners, but only after I check/uncheck the "check for online" in settings, so cancel that.

**Comment by Sentilix** [comment]
First: don't use the 1.2 version - always use the latest stable version. You can find it in the Release section: https://github.com/Sentilix/sota/releases
You can circumvent the blue messages by going to the settings (trhe cockwheel) and click Messages. This sets the (missing) messages to their default values, and you won't see the error anymore.

DKP for offliners works if you enable the option, as you just found out :-)
The reason for the original online check was that people needed to be online to check if they were in the correct zone.
Enabling OFFLINE DKP still does the check for those online, but those offline gets DKP even they are in Ironforge.
